apiVersion: apps/v1
kind: Service
metadata:
  name: socket-io-chat
  namespace: poc
spec:
  selector:
    matchLabels:
      name: socket-io-chat
  template:
    metadata:
      labels:
        name: socket-io-chat
    spec:
      containers:
        - name: socket-io-chat
          image: friedrichmatheus/socket-io-chat:latest
          ports:
            - containerPort: 3000